services:
  postgres:
    image: postgres:18-alpine
    container_name: go_todo_db_dev
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d todo_db"]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_dev:/var/lib/postgresql

  prometheus:
    image: prom/prometheus:v3.9.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "app:host-gateway"

  grafana:
    image: grafana/grafana:12.3.2
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./infra/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./infra/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./infra/grafana/dashboards:/etc/grafana/dashboards

  node_exporter:
    image: prom/node-exporter:v1.10.2
    ports:
      - "9100:9100"

  loki:
    image: grafana/loki:3.3.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data_dev:/loki

  alloy:
    image: grafana/alloy:v1.6.1
    volumes:
      - ./infra/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy_data_dev:/var/lib/alloy/data
    command: run --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    user: root # To read /var/lib/docker/containers logs
    depends_on:
      - loki

volumes:
  postgres_data_dev:
  loki_data_dev:
  alloy_data_dev:
