services:
  postgres:
    image: postgres:18-alpine
    container_name: go_todo_db_dev
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d todo_db"]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_dev:/var/lib/postgresql

volumes:
  postgres_data_dev:
