# This file is templated by envsubst on container startup

global:
  scrape_interval: 5s # For demo only

scrape_configs:
  - job_name: 'goroutine_app'
    static_configs:
      - targets: ['app:${ADMIN_PORT}']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
